// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtkJGUpLZz1zSCLFG5xouqzsJfdCohU6U',
    appId: '1:560723909414:web:9eb267de07879a74fd3fe7',
    messagingSenderId: '560723909414',
    projectId: 'linkify-42653',
    authDomain: 'linkify-42653.firebaseapp.com',
    storageBucket: 'linkify-42653.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBERpvDh6R8JMFdBowOTgdqLRKIgXutzBk',
    appId: '1:560723909414:android:b9d465815d611aa8fd3fe7',
    messagingSenderId: '560723909414',
    projectId: 'linkify-42653',
    storageBucket: 'linkify-42653.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-2xfYJTTx9FX324_AVGvAP88v2TMv5N0',
    appId: '1:560723909414:ios:f9d9ec500ca4ee28fd3fe7',
    messagingSenderId: '560723909414',
    projectId: 'linkify-42653',
    storageBucket: 'linkify-42653.appspot.com',
    iosBundleId: 'com.example.linkify',
  );
}
